server:
  port: 8082

spring:
  h2:
    console:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: create


  datasource:
    url: jdbc:h2:mem:usuariodb
    username: user
    password: 123
    driver-class-name: org.h2.Driver
